services:
  - type: web
    name: cv-elkin
    env: python
    plan: free
    buildCommand: ./build.sh
    startCommand: gunicorn cv_elkin.wsgi:application
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: WEB_CONCURRENCY
        value: "4"
      # IMPORTANTE: Quita DATABASE_URL si no creaste la BD
      # - key: DATABASE_URL
      #   fromDatabase:
      #     name: cv-elkin-db
      #     property: connectionString
