services:
  - type: web
    name: cv-elkin
    env: python
    buildCommand: |
      pip install --upgrade pip
      pip install Django==4.2.10 gunicorn==21.2.0 whitenoise==6.6.0 dj-database-url==2.1.0 psycopg2-binary==2.9.9 cloudinary==1.38.0 django-cloudinary-storage==0.3.0
      python manage.py migrate
      python manage.py collectstatic --noinput
    startCommand: gunicorn cv_elkin.wsgi:application
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.12