services:
  - type: web
    name: cv-elkin
    env: python
    buildCommand: |
      pip install -r requirements.txt
      python manage.py migrate
      python manage.py collectstatic --noinput
    startCommand: gunicorn cv_elkin.wsgi:application
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: postgresql
          property: connectionString
      - key: DJANGO_SUPERUSER_USERNAME
        value: admin
      - key: DJANGO_SUPERUSER_EMAIL
        value: elkinjoshuadelgadolopez68@gmail.com
      - key: DJANGO_SUPERUSER_PASSWORD
        value: Admin123456!
      - key: DEBUG
        value: false